Repository kakao-tech-campus-2nd-step3/Team8_FE, pull requests merged in 2024-11, with the labels that each got.

#130 시니또용 콜백 조회 API 및 기능 수정
  src/app/routes/router.tsx
  src/pages/sinitto/call-back/detail/CallBackDetailPage.tsx
  src/pages/sinitto/call-back/detail/components/menu/CallbackMenu.tsx
  src/pages/sinitto/call-back/list/api/callback-list.api.ts
  src/pages/sinitto/call-back/list/api/get-call-backs.api.ts
  src/pages/sinitto/call-back/list/api/types/callbacks.response.ts
  src/pages/sinitto/call-back/list/api/types/index.ts
  src/pages/sinitto/guide-line/SinittoGuideLinePage.tsx
  src/pages/sinitto/guide-line/api/get-guideline.api.ts
  src/pages/sinitto/guide-line/api/hooks/useGetGuideline.ts
  src/pages/sinitto/guide-line/api/types/guideline.response.ts
  src/pages/sinitto/guide-line/components/container/Container.tsx
  src/pages/sinitto/guide-line/components/container/index.ts
  src/shared/types/callback.response.ts
Labels: ✨ Feature, 📡 API

#140 [기능구현] 서비스 이용내역 페이지
  src/pages/guard/service-history/ServiceHistoryPage.tsx
  src/pages/guard/service-history/api/delete-hello-call.api.ts
  src/pages/guard/service-history/api/get-callback-history.api.ts
  src/pages/guard/service-history/api/get-hello-history.api.ts
  src/pages/guard/service-history/api/hooks/index.ts
  src/pages/guard/service-history/api/hooks/useCompleteCallback.ts
  src/pages/guard/service-history/api/hooks/useDeleteHelloCall.ts
  src/pages/guard/service-history/api/hooks/useGetCallbackHistory.ts
  src/pages/guard/service-history/api/hooks/useGetHelloHistoryList.ts
  src/pages/guard/service-history/api/hooks/useHelloServiceHistory.ts
  src/pages/guard/service-history/api/hooks/useModifyHelloCall.ts
  src/pages/guard/service-history/api/index.ts
  src/pages/guard/service-history/api/make-callback-completed.api.ts
  src/pages/guard/service-history/api/modify-hello-call.api.ts
  src/pages/guard/service-history/components/callback-history-text/CallbackHistoryText.tsx
  src/pages/guard/service-history/components/callback-history-text/index.ts
  src/pages/guard/service-history/components/callback-history/CallbackHistoryDetail.tsx
  src/pages/guard/service-history/components/callback-history/index.ts
  src/pages/guard/service-history/components/hello-service-history-text/HelloServiceHistoryText.tsx
  src/pages/guard/service-history/components/hello-service-history-text/index.ts
  src/pages/guard/service-history/components/hello-service-history/HelloServiceHistory.tsx
  src/pages/guard/service-history/components/hello-service-history/index.ts
  src/pages/guard/service-history/components/historydetail/HistoryDetail.tsx
  src/pages/guard/service-history/components/historydetail/index.ts
  src/pages/guard/service-history/components/index.ts
  src/pages/guard/service-history/components/service-status/ServiceStatus.tsx
  src/pages/guard/service-history/components/service-status/index.ts
  src/pages/guard/service-history/index.ts
  src/pages/guard/service-history/types/index.ts
  src/pages/sinitto/hello-call-service/api/types/service-detail.response.ts
  src/shared/api/instance/Instance.tsx
  src/shared/api/point/point-log.api.ts
  src/shared/utils/date/dateUtils.ts
  src/shared/utils/status/statusUtils.ts
Labels: ✨ Feature, 📡 API, ♻️ Refactoring

#142 https로 로컬환경 열기
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: 🚀 Deploy

#135 시니또 정보 조회 api 기능 수정
  src/pages/common/redirect/components/redirect-section/RedirectSection.tsx
  src/pages/common/register/RegisterPage.tsx
  src/pages/sinitto/mypage/SinittoMypage.tsx
  src/pages/sinitto/mypage/api/hooks/index.ts
  src/pages/sinitto/mypage/api/hooks/useSinittoInfo.ts
  src/pages/sinitto/mypage/api/index.ts
  src/pages/sinitto/mypage/api/sinitto-information.api.ts
  src/pages/sinitto/mypage/api/types/index.ts
  src/pages/sinitto/mypage/api/types/sinitto-information.request.ts
  src/pages/sinitto/mypage/api/types/sinitto-information.response.ts
  src/pages/sinitto/mypage/components/account-info-box/AccountInfoBox.tsx
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/pages/sinitto/sinitto-main/api/sinitto-info.api.ts
  src/pages/sinitto/sinitto-main/api/types/sinitto-info.response.ts
Labels: 😡 Bug Fix, ✨ Feature

#143 메인페이지 디자인 수정
  package.json
  pnpm-lock.yaml
  src/pages/assets/main/star-icon-unfill.svg
  src/pages/common/main/MainPage.tsx
  src/pages/common/main/assets/call-illust.svg
  src/pages/common/main/assets/point-illust.svg
  src/pages/common/main/components/intro/Intro.tsx
  src/pages/common/main/components/intro/index.ts
  src/pages/common/main/components/login-button/LoginButton.tsx
  src/pages/common/main/components/review-box/ReviewBox.tsx
  src/pages/common/main/components/swipe-page/first-page/FirstPage.tsx
  src/pages/common/main/components/swipe-page/first-page/index.ts
  src/pages/common/main/components/swipe-page/index.ts
  src/pages/common/main/components/swipe-page/second-page/SecondPage.tsx
  src/pages/common/main/components/swipe-page/second-page/index.ts
  src/pages/common/main/components/swipe-page/third-page/ThirdPage.tsx
  src/pages/common/main/components/swipe-page/third-page/index.ts
Labels: 🎨 Design

#147 시니또 안부전화 서비스 기능구현
  .github/workflows/ci.yml
  src/app/routes/path.ts
  src/pages/guard/guide-line/api/view-senior-all-guideline.api.ts
  src/pages/sinitto/hello-call-list/HelloCallListPage.tsx
  src/pages/sinitto/hello-call-service/HelloCallServicePage.tsx
  src/pages/sinitto/hello-call-service/api/accept-hello-call.api.ts
  src/pages/sinitto/hello-call-service/api/cancel-hello-call.api.ts
  src/pages/sinitto/hello-call-service/api/hooks/index.ts
  src/pages/sinitto/hello-call-service/api/hooks/usePutAcceptHelloCall.ts
  src/pages/sinitto/hello-call-service/api/hooks/usePutCancelHelloCall.ts
  src/pages/sinitto/hello-call-service/api/index.ts
  src/pages/sinitto/hello-call-service/api/types/index.ts
  src/pages/sinitto/hello-call-service/api/types/service-detail.response.ts
  src/pages/sinitto/hello-call-service/api/types/sinitto-hello-call.response.ts
  src/pages/sinitto/hello-call-service/components/service-detail/ServiceDetail.tsx
  src/pages/sinitto/hello-call-service/hooks/index.ts
  src/pages/sinitto/hello-call-service/hooks/useFormatPhoneNumber.ts
  src/pages/sinitto/hello-call-service/hooks/useServiceDate.ts
  src/shared/api/instance/Instance.tsx
Labels: ✨ Feature, 📡 API

#145 QA 수정사항 진행
  src/pages/assets/guard-main/list.svg
  src/pages/guard/guard-main/GuardMainPage.tsx
  src/pages/guard/guard-main/components/header/Header.tsx
  src/pages/guard/guide-line/api/hooks/useGuidelineInfo.ts
  src/pages/guard/mypage/GuardMyPage.tsx
  src/pages/guard/service-history/api/hooks/index.ts
  src/pages/guard/service-history/api/hooks/useHelloServiceHistory.ts
  src/pages/guard/service-history/api/hooks/useModifyHelloCall.ts
  src/pages/guard/service-history/api/index.ts
  src/pages/guard/service-history/api/modify-hello-call.api.ts
  src/pages/guard/service-history/components/hello-service-history/HelloServiceHistory.tsx
  src/pages/sinitto/mypage/SinittoMypage.tsx
  src/pages/sinitto/mypage/components/account-info-box/AccountInfoBox.tsx
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/shared/api/hooks/useWithdrawal.ts
  src/shared/api/index.ts
  src/shared/api/logout.api.ts
  src/shared/api/withdrawal.api.ts
  src/shared/components/features/mypage/index.ts
  src/shared/components/features/mypage/point-box/PointBox.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
  src/shared/components/features/mypage/withdrawal-button/Withdrawal.tsx
  src/shared/components/features/mypage/withdrawal-button/index.ts
  src/shared/hooks/point/useChargePoint.ts
  src/shared/hooks/point/useWithdrawPoint.ts
Labels: 😡 Bug Fix, ✨ Feature

#152 콜백 요청 및 안부전화 요청 서비스 신청 목록
  src/app/routes/path.ts
  src/app/routes/router.tsx
  src/pages/common/main/MainPage.tsx
  src/pages/guard/hello-call-report/api/apply-call-list.api.ts
  src/pages/guard/hello-call-report/api/hooks/useGetApplyCallList.ts
  src/pages/guard/hello-call-report/api/index.ts
  src/pages/guard/hello-call-report/api/types/apply-call-list.response.ts
  src/pages/guard/hello-call-report/api/types/index.ts
  src/pages/sinitto/hello-call-report/api/hooks/index.ts
  src/pages/sinitto/hello-call-report/api/hooks/usePostWriteReport.ts
  src/pages/sinitto/hello-call-report/api/index.ts
  src/pages/sinitto/hello-call-report/api/types/index.ts
  src/pages/sinitto/hello-call-report/api/types/write-report.request.ts
  src/pages/sinitto/hello-call-report/api/write-report.api.ts
  src/pages/sinitto/hello-call-report/components/report-detail/ReportDetail.tsx
  src/pages/sinitto/hello-call-service/api/hooks/index.ts
  src/pages/sinitto/hello-call-service/api/hooks/usePutCancelHelloCall.ts
  src/pages/sinitto/index.ts
  src/pages/sinitto/service-history/SinittoServiceHistory.tsx
  src/pages/sinitto/service-history/api/accepted-call-back-list.api.ts
  src/pages/sinitto/service-history/api/apply-hello-call-list.api.ts
  src/pages/sinitto/service-history/api/cancel-hello-call.api.ts
  src/pages/sinitto/service-history/api/hooks/index.ts
  src/pages/sinitto/service-history/api/hooks/useGetAcceptedCallBackList.ts
  src/pages/sinitto/service-history/api/hooks/useGetApplyHelloCallList.ts
  src/pages/sinitto/service-history/api/hooks/usePutCancelHelloCall.ts
  src/pages/sinitto/service-history/api/index.ts
  src/pages/sinitto/service-history/api/types/accepted-call-back-list.response.ts
  src/pages/sinitto/service-history/api/types/apply-hello-call-list.response.ts
  src/pages/sinitto/service-history/api/types/index.ts
  src/pages/sinitto/service-history/api/types/sinitto-hello-call.response.ts
  src/pages/sinitto/service-history/components/common/call-back-service-list/CallBackServiceList.tsx
  src/pages/sinitto/service-history/components/common/call-back-service-list/index.ts
  src/pages/sinitto/service-history/components/common/hello-call-service-list/HelloCallServiceList.tsx
  src/pages/sinitto/service-history/components/common/hello-call-service-list/index.ts
  src/pages/sinitto/service-history/components/common/index.ts
  src/pages/sinitto/service-history/components/features/index.ts
  src/pages/sinitto/service-history/components/features/status-button/StatusButton.tsx
  src/pages/sinitto/service-history/components/features/status-button/index.ts
  src/pages/sinitto/service-history/components/features/text-area/TextArea.tsx
  src/pages/sinitto/service-history/components/features/text-area/index.ts
  src/pages/sinitto/service-history/components/index.ts
  src/pages/sinitto/service-history/data/day-schema/DaySchema.ts
  src/pages/sinitto/service-history/data/day-schema/index.ts
  src/pages/sinitto/service-history/data/index.ts
  src/pages/sinitto/service-history/data/text-schema/TextSchema.ts
  src/pages/sinitto/service-history/data/text-schema/index.ts
  src/pages/sinitto/service-history/hooks/index.ts
  src/pages/sinitto/service-history/hooks/useArrayFormatting.ts
  src/pages/sinitto/service-history/hooks/useDateFormatting.ts
  src/pages/sinitto/service-history/index.ts
  src/pages/sinitto/sinitto-main/SinittoMainPage.tsx
  src/pages/sinitto/sinitto-main/components/common/index.ts
  src/pages/sinitto/sinitto-main/components/common/service-history-button/ServiceHistoryButton.tsx
  src/pages/sinitto/sinitto-main/components/common/service-history-button/index.ts
  src/pages/sinitto/sinitto-main/components/common/sinitto-name/SinittoName.tsx
Labels: ✨ Feature, 🎨 Design, 📡 API

#154 시니또 메인화면 수정
  src/pages/sinitto/sinitto-main/components/common/call-back-apply/CallBackApply.tsx
  src/pages/sinitto/sinitto-main/components/common/hello-call-apply/HelloCallApply.tsx
  src/pages/sinitto/sinitto-main/components/features/response-box/ResponseBox.tsx
Labels: ✨ Feature, 🎨 Design

#155 페이지 Protect 기능 추가
  src/app/routes/components/index.ts
  src/app/routes/components/protected-route/ProtectedRoute.tsx
  src/app/routes/components/protected-route/index.ts
  src/app/routes/path.ts
  src/app/routes/router.tsx
Labels: ✨ Feature

#157 [QA] 시니또 콜백 페이지 관련 오류 수정
  src/pages/sinitto/call-back/detail/api/complete-call-back.api.ts
  src/pages/sinitto/call-back/detail/api/hooks/useAcceptCallback.ts
  src/pages/sinitto/call-back/detail/components/menu/CallbackMenu.tsx
Labels: 😡 Bug Fix

#162 [QA] 시니또 콜백 오류 메시지 수정
  src/pages/sinitto/call-back/detail/api/hooks/useAcceptCallback.ts
  src/pages/sinitto/call-back/detail/api/hooks/useCancelCallback.ts
  src/pages/sinitto/call-back/detail/api/hooks/useCompleteCallback.ts
  src/pages/sinitto/call-back/detail/components/menu/CallbackMenu.tsx
Labels: 😡 Bug Fix

#169 시니또 서비스 신청내역 기능 수정
  src/app/routes/router.tsx
  src/pages/sinitto/service-history/SinittoServiceHistory.tsx
Labels: 😡 Bug Fix

#175 시니또 서비스 이용내역 수정 및 아이콘 적용
  index.html
  public/favicon.png
  public/vite.svg
  src/pages/sinitto/service-history/SinittoServiceHistory.tsx
Labels: 😡 Bug Fix, 🎨 Design

#178 시니또 서비스 이용 내역 문구 수정
  index.html
  src/pages/sinitto/service-history/data/text-schema/TextSchema.ts
Labels: 🎨 Design

#176 [QA] 수정사항 반영
  src/app/routes/path.ts
  src/app/routes/router.tsx
  src/pages/guard/guide-line/api/hooks/useGuidelineInfo.ts
  src/pages/guard/guide-line/components/guide-info-box/GuideLineInfo.tsx
  src/pages/guard/guide-line/components/guide-register-box/GuidelineRegisterBox.tsx
  src/pages/guard/hello-call-report/GuardReportPage.tsx
  src/pages/guard/hello-call-report/api/hooks/usePutCompleteHelloCall.ts
  src/pages/guard/hello-call-report/asset/heartIcon.svg
  src/pages/guard/hello-call-report/components/GuardReportDetail.tsx
  src/pages/guard/hello-call-report/components/index.ts
  src/pages/guard/hello-call-report/index.ts
  src/pages/guard/index.ts
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
  src/pages/guard/register/api/hooks/useSeniorInfo.ts
  src/pages/guard/register/components/senior-info/senior-info-box/SeniorInfo.tsx
  src/pages/guard/register/components/senior-register-box/SeniorRegisterBox.tsx
  src/pages/guard/review/SinittoReviewPage.tsx
  src/pages/guard/review/api/hooks/index.ts
  src/pages/guard/review/api/hooks/usePostReview.ts
  src/pages/guard/review/api/index.ts
  src/pages/guard/review/api/review.api.ts
  src/pages/guard/review/api/types/index.ts
  src/pages/guard/review/api/types/review.request.ts
  src/pages/guard/service-history/ServiceHistoryPage.tsx
  src/pages/guard/service-history/api/hooks/useCompleteCallback.ts
  src/pages/guard/service-history/components/hello-service-history-text/HelloServiceHistoryText.tsx
  src/pages/guard/service-history/components/hello-service-history/HelloServiceHistory.tsx
  src/pages/sinitto/mypage/components/account-info-box/AccountInfoBox.tsx
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/shared/api/hooks/useLogout.ts
  src/shared/assets/index.ts
  src/shared/assets/mail-icon.svg
  src/shared/components/features/mypage/point-box/PointBox.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
  src/shared/hooks/point/pointStatusMapping.ts
  src/shared/hooks/point/useChargePoint.ts
  src/shared/utils/account-number/validateAccountNumber.ts
  src/shared/utils/index.ts
  src/shared/utils/name/index.ts
  src/shared/utils/name/validateName.ts
  src/shared/utils/phone-number/index.ts
  src/shared/utils/phone-number/validatePhoneNumber.ts
Labels: 😡 Bug Fix, ✨ Feature, ♻️ Refactoring

#182 PWA 적용
  .gitignore
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/favicon.png
  public/icons/apple-touch-icon-180x180.png
  public/icons/favicon.ico
  public/icons/icon-144x144.png
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/icons/maskable-icon-512x512.png
  src/shared/hooks/index.ts
  src/shared/hooks/useIntersectionObserver.ts
  sw.js
  tsconfig.json
  vite.config.ts
Labels: 🚀 Deploy, 🎨 Design

#186 서비스 이용 방법 한번에 이해하기 페이지 제작
  public/image/service-manual1.png
  public/image/service-manual2.png
  public/image/service-manual3.png
  public/image/service-manual4.png
  public/image/service-manual5.png
  src/app/routes/path.ts
  src/app/routes/router.tsx
  src/pages/common/index.ts
  src/pages/common/service-manual/ServiceManualPage.tsx
  src/pages/common/service-manual/components/ManualDetail.tsx
  src/pages/common/service-manual/components/index.ts
  src/pages/common/service-manual/index.ts
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
Labels: 🎨 Design

#187 이미지가 배포서버에 뜨지 않는 오류 해결
  src/pages/common/service-manual/ServiceManualPage.tsx
Labels: 😡 Bug Fix

#189 유틸함수 테스트코드 작성 + 시니어 사용할 서비스 번호 수정
  package.json
  src/pages/guard/guard-main/GuardMainPage.tsx
  src/pages/guard/service-history/components/callback-history/CallbackHistoryDetail.tsx
  src/pages/guard/service-history/components/hello-service-history/HelloServiceHistory.tsx
  src/pages/guard/service-history/components/service-status/ServiceStatus.tsx
  src/pages/sinitto/mypage/components/account-info-box/AccountInfoBox.tsx
  src/shared/utils/dateUtils.ts
  src/shared/utils/formatPhoneNumber.ts
  src/shared/utils/index.ts
  src/shared/utils/name/index.ts
  src/shared/utils/phone-number/formatPhoneNumber.ts
  src/shared/utils/phone-number/index.ts
  src/shared/utils/statusUtils.ts
  src/shared/utils/test/dateUtils.test.ts
  src/shared/utils/test/formatPhoneNumber.test.ts
  src/shared/utils/test/statusUtils.test.ts
  src/shared/utils/test/validateInformation.test.ts
  src/shared/utils/validateAccountNumber.ts
  src/shared/utils/validateName.ts
  src/shared/utils/validatePhoneNumber.ts
Labels: ✅ Test Code

#190 테스트 코드 작성 및 테스트 오류 예외처리
  .babelrc
  __mocks__/fileMock.d.ts
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  babel.config.js
  jest.config.ts
  package.json
  pnpm-lock.yaml
  src/declaration.d.ts
  src/pages/guard/hello-call-apply/HelloCallApplyPage.tsx
  src/pages/guard/hello-call-apply/components/service-apply/ServiceApply.tsx
  src/pages/sinitto/hello-call-service/HelloCallServicePage.tsx
  src/pages/sinitto/hello-call-service/__test__/useServiceDate.test.ts
  src/pages/sinitto/hello-call-service/hooks/index.ts
  src/pages/sinitto/hello-call-service/hooks/useFormatPhoneNumber.ts
  src/pages/sinitto/hello-call-service/hooks/useHelloCallService.ts
  tsconfig.json
  tsconfig.test.json
Labels: 😡 Bug Fix, ✅ Test Code

#201 가이드라인 타입 추가
  src/pages/guard/guide-line/components/guide-register-box/GuidelineRegisterBox.tsx
  src/shared/components/common/guide-line-button/GuideLineButton.tsx
Labels: ✨ Feature

#203 서비스 이용방법 한 번에 이해하기 페이지 UI 수정
  public/image/service-manual1.png
  public/image/service-manual2.png
  public/image/service-manual3.png
  public/image/service-manual4.png
  public/image/service-manual5.png
  src/pages/common/service-manual/ServiceManualPage.tsx
  src/pages/common/service-manual/components/ManualDetail.tsx
Labels: 🎨 Design

#206 기타 수정 사항 반영
  src/pages/common/register/api/index.ts
  src/pages/common/register/api/user-register.ts
  src/pages/common/register/components/index.ts
  src/pages/common/register/components/register-fields/FormField.tsx
  src/pages/common/register/components/register-fields/RegisterFields.tsx
  src/pages/common/register/components/register-fields/form-fields/index.ts
  src/pages/common/register/components/register-fields/index.ts
  src/pages/common/register/hooks/index.ts
  src/pages/common/register/hooks/useRegister.ts
  src/pages/common/register/index.ts
  src/pages/common/register/store/api/user-register.ts
  src/pages/common/register/types/formValue.ts
  src/pages/common/register/types/index.ts
  src/pages/common/register/types/signup.request.ts
  src/pages/common/register/types/signup.response.ts
  src/pages/common/register/ui/RegisterPage.tsx
  src/pages/common/register/ui/index.ts
  src/pages/common/service-manual/index.ts
  src/pages/common/service-manual/ui/ServiceManualPage.tsx
  src/pages/common/service-manual/ui/index.ts
  src/pages/guard/guard-main/ui/GuardMainPage.tsx
  src/pages/guard/service-history/hooks/index.ts
  src/pages/guard/service-history/hooks/usePagination.ts
  src/pages/guard/service-history/ui/ServiceHistoryPage.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
Labels: 😡 Bug Fix, 🎨 Design

#207 코드 리팩토링 및 테스트코드 작성
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
  src/pages/guard/mypage/hooks/useGuardProfile.ts
  src/pages/guard/mypage/ui/GuardMyPage.tsx
  src/pages/sinitto/hello-call-report/hooks/usePostWriteReport.ts
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/pages/sinitto/mypage/hooks/useSinittoProfile.ts
  src/shared/api/point/point-log.api.ts
  src/shared/api/point/point.api.ts
  src/shared/components/features/mypage/point-box/PointBox.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
  src/shared/constants/index.ts
  src/shared/constants/point/index.ts
  src/shared/constants/point/pointQueryKey.ts
  src/shared/hooks/point/useChargePoint.ts
  src/shared/hooks/point/useGetPointInfo.ts
  src/shared/hooks/point/useWithdrawPoint.ts
  src/shared/utils/test/validateInformation.test.ts
Labels: ✅ Test Code, ♻️ Refactoring

#213 콜백 서비스 완료대기 -> 완료 시 콜백 내역 refetch 되지 않던 문제 해결
  src/pages/common/register/apis/index.ts
  src/pages/common/register/apis/user-register.ts
  src/pages/common/register/hooks/useRegister.ts
  src/pages/common/register/index.ts
  src/pages/guard/guide-line/api/index.ts
  src/pages/guard/guide-line/apis/add-guideline.api.ts
  src/pages/guard/guide-line/apis/delete-guideline.api.ts
  src/pages/guard/guide-line/apis/index.ts
  src/pages/guard/guide-line/apis/modify-guideline.api.ts
  src/pages/guard/guide-line/apis/view-senior-all-guideline.api.ts
  src/pages/guard/guide-line/apis/view-specific-guideline.api.ts
  src/pages/guard/guide-line/hooks/useAddGuideline.ts
  src/pages/guard/guide-line/hooks/useDeleteGuideline.ts
  src/pages/guard/guide-line/hooks/useGetSeniorAllGuideines.ts
  src/pages/guard/guide-line/hooks/useGetViewSpecificGuideline.ts
  src/pages/guard/guide-line/hooks/useModifyGuideline.ts
  src/pages/guard/guide-line/index.ts
  src/pages/guard/index.ts
  src/pages/guard/mypage/api/index.ts
  src/pages/guard/mypage/apis/all-senior-info.api.ts
  src/pages/guard/mypage/apis/guard-information.api.ts
  src/pages/guard/mypage/apis/index.ts
  src/pages/guard/mypage/hooks/useGetAllSeniorInfo.ts
  src/pages/guard/mypage/hooks/useGetGuardInformation.ts
  src/pages/guard/mypage/hooks/useModifyGuardInfo.ts
  src/pages/guard/mypage/index.ts
  src/pages/guard/register/api/index.ts
  src/pages/guard/register/apis/index.ts
  src/pages/guard/register/apis/senior-info.api.ts
  src/pages/guard/register/hooks/useAddSeniorInfo.ts
  src/pages/guard/register/hooks/useDeleteSeniorInfo.ts
  src/pages/guard/register/hooks/useEditSeniorInfo.ts
  src/pages/guard/register/index.ts
  src/pages/guard/review/apis/index.ts
  src/pages/guard/review/apis/review.api.ts
  src/pages/guard/review/hooks/usePostReview.ts
  src/pages/guard/review/index.ts
  src/pages/guard/service-history/hooks/useCompleteCallback.ts
  src/pages/guard/service-history/hooks/useHistoryData.ts
  src/pages/guard/service-history/hooks/useServiceStatus.ts
  src/pages/sinitto/mypage/apis/index.ts
  src/pages/sinitto/mypage/apis/sinitto-information.api.ts
  src/pages/sinitto/mypage/hooks/useSinittoInfo.ts
  src/pages/sinitto/mypage/index.ts
  src/pages/sinitto/point/.gitkeep
Labels: 😡 Bug Fix, ♻️ Refactoring

#214 폴더구조 수정
  src/pages/assets/callback/arrow.png
  src/pages/assets/onboard/call-illust.svg
  src/pages/assets/onboard/point-illust.svg
  src/pages/common/onboard/components/swipe-page/second-page/SecondPage.tsx
  src/pages/common/onboard/components/swipe-page/third-page/ThirdPage.tsx
  src/pages/guard/guide-line/apis/index.ts
  src/pages/guard/guide-line/components/guide-register-box/GuidelineRegisterBox.tsx
  src/pages/guard/guide-line/hooks/index.ts
  src/pages/guard/guide-line/hooks/useAddGuideline.ts
  src/pages/guard/guide-line/hooks/useGuidelineForm.ts
  src/pages/guard/guide-line/hooks/useGuidelinePlaceholder.ts
  src/pages/guard/mypage/apis/guard-information.api.ts
  src/pages/guard/mypage/apis/index.ts
  src/pages/guard/mypage/hooks/useGetGuardInformation.ts
  src/pages/guard/register/apis/index.ts
  src/pages/sinitto/call-back/detail/index.ts
  src/pages/sinitto/call-back/detail/ui/CallBackDetailPage.tsx
  src/pages/sinitto/call-back/detail/ui/index.ts
  src/pages/sinitto/call-back/list/api/hooks/index.ts
  src/pages/sinitto/call-back/list/api/index.ts
  src/pages/sinitto/call-back/list/apis/callback-list.api.ts
  src/pages/sinitto/call-back/list/apis/get-call-backs.api.ts
  src/pages/sinitto/call-back/list/apis/index.ts
  src/pages/sinitto/call-back/list/components/request-row/RequestRow.tsx
  src/pages/sinitto/call-back/list/hooks/index.ts
  src/pages/sinitto/call-back/list/hooks/useCallbacks.ts
  src/pages/sinitto/call-back/list/hooks/useGetCallbacks.ts
  src/pages/sinitto/call-back/list/hooks/useInfiniteScroll.ts
  src/pages/sinitto/call-back/list/hooks/useRequestNavigation.ts
  src/pages/sinitto/call-back/list/hooks/useTimeAgo.ts
  src/pages/sinitto/call-back/list/index.ts
  src/pages/sinitto/call-back/list/types/callbacks.response.ts
  src/pages/sinitto/call-back/list/types/index.ts
  src/pages/sinitto/call-back/list/ui/CallBackListPage.tsx
  src/pages/sinitto/call-back/list/ui/index.ts
  src/pages/sinitto/guide-line/api/hooks/index.ts
  src/pages/sinitto/guide-line/api/types/index.ts
  src/pages/sinitto/guide-line/apis/get-guideline.api.ts
  src/pages/sinitto/guide-line/apis/index.ts
  src/pages/sinitto/guide-line/hooks/index.ts
  src/pages/sinitto/guide-line/hooks/useCategoryName.ts
  src/pages/sinitto/guide-line/hooks/useGetGuideline.ts
  src/pages/sinitto/guide-line/hooks/useGuideLineData.ts
  src/pages/sinitto/guide-line/hooks/useGuideLineErrorHandling.ts
  src/pages/sinitto/guide-line/index.ts
  src/pages/sinitto/guide-line/types/category.ts
  src/pages/sinitto/guide-line/types/guideline.response.ts
  src/pages/sinitto/guide-line/types/index.ts
  src/pages/sinitto/guide-line/ui/SinittoGuideLinePage.tsx
  src/pages/sinitto/guide-line/ui/index.ts
  src/pages/sinitto/review/ReviewPage.tsx
  src/pages/sinitto/review/components/.keep
  src/pages/sinitto/sinitto-main/components/common/call-back-apply/CallBackApply.tsx
  src/pages/sinitto/sinitto-main/hooks/useCallBackData.ts
Labels: ♻️ Refactoring

#215 성능을 개선해봅시다!
  index.html
  package.json
  pnpm-lock.yaml
  src/app/routes/components/index.ts
  src/app/routes/components/lazy-loading/LazyLoading.ts
  src/app/routes/components/lazy-loading/index.ts
  src/app/routes/router.tsx
  src/main.tsx
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
  src/pages/guard/service-history/hooks/useHistoryData.ts
  src/pages/guard/service-history/ui/ServiceHistoryPage.tsx
  src/pages/sinitto/mypage/ui/SinittoMyPage.tsx
  src/pages/sinitto/mypage/ui/index.ts
  src/pages/sinitto/service-history/ui/SinittoServiceHistoryPage.tsx
  src/pages/sinitto/service-history/ui/index.ts
Labels: 😡 Bug Fix, ♻️ Refactoring

#216 isSinitto 속성에 맞게 페이지 이동
  src/app/routes/components/protected-route/ProtectedRoute.tsx
  src/pages/common/dummy-redirect/DummyRedirectPage.tsx
  src/pages/common/redirect/components/redirect-section/RedirectSection.tsx
  src/pages/common/register/ui/RegisterPage.tsx
  src/shared/utils/storage/authStorage.ts
Labels: 😡 Bug Fix

#218 성능 최적화 (2)
  index.html
  package.json
  pnpm-lock.yaml
  src/app/routes/components/index.ts
  src/app/routes/components/lazy-loading/LazyLoading.ts
  src/app/routes/components/lazy-loading/index.ts
  src/app/routes/router.tsx
  src/global.d.ts
  src/pages/assets/shared/hello-call.png
  src/pages/assets/shared/hello-call.webp
  src/pages/guard/guard-main/components/hello-call-apply/HelloCallApply.tsx
  src/pages/guard/hello-call-apply/components/service-total/ServiceTotal.tsx
  src/pages/sinitto/hello-call-list/ui/HelloCallListPage.tsx
  src/pages/sinitto/sinitto-main/components/common/call-back-apply/CallBackApply.tsx
  src/pages/sinitto/sinitto-main/components/common/hello-call-apply/HelloCallApply.tsx
  tsconfig.json
  vite.config.ts
Labels: ♻️ Refactoring

#232 페이지 lazy loading 및 스켈레톤 UI 적용
  src/pages/guard/guide-line/ui/GuideLinePage.tsx
  src/pages/guard/hello-call-report/components/GuardReportDetail.tsx
  src/pages/guard/hello-call-report/ui/GuardReportPage.tsx
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
  src/pages/guard/mypage/ui/GuardMyPage.tsx
  src/pages/guard/register/ui/SeniorRegisterPage.tsx
  src/pages/sinitto/call-back/detail/components/menu/CallbackMenu.tsx
  src/pages/sinitto/call-back/detail/ui/CallBackDetailPage.tsx
  src/pages/sinitto/call-back/list/ui/CallBackListPage.tsx
  src/pages/sinitto/guide-line/ui/SinittoGuideLinePage.tsx
  src/pages/sinitto/mypage/components/account-info-box/AccountInfoBox.tsx
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/pages/sinitto/mypage/hooks/useAccountInfo.ts
  src/pages/sinitto/mypage/hooks/useSinittoProfile.ts
  src/pages/sinitto/mypage/ui/SinittoMyPage.tsx
  src/shared/components/features/mypage/point-box/PointBox.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
Labels: ♻️ Refactoring
