Repository kakao-tech-campus-2nd-step3/Team8_FE, pull requests merged in 2024-09, with the labels that each got.

#2 FE 개발 환경 세팅 및 폴더구조 세팅
  .babelrc
  .eslintrc.json
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc.json
  index.html
  jest.config.ts
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  public/vite.svg
  src/App.tsx
  src/__test__/.gitkeep
  src/api/hooks/common/auth/.gitkeep
  src/api/hooks/guard/guide-line/.gitkeep
  src/api/hooks/guard/mypage/.gitkeep
  src/api/hooks/guard/point/.gitkeep
  src/api/hooks/guard/register/.gitkeep
  src/api/hooks/guard/review/.gitkeep
  src/api/hooks/siniddo/call-back/.gitkeep
  src/api/hooks/siniddo/guide-line/.gitkeep
  src/api/hooks/siniddo/hello-call/.gitkeep
  src/api/hooks/siniddo/mypage/.gitkeep
  src/api/hooks/siniddo/point/.gitkeep
  src/api/instance/index.ts
  src/assets/react.svg
  src/components/features/login/index.tsx
  src/components/home/index.tsx
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/mocks/.gitkeep
  src/pages/guard/guide-line/.gitkeep
  src/pages/guard/mypage/.gitkeep
  src/pages/guard/point/.gitkeep
  src/pages/guard/register/.gitkeep
  src/pages/guard/review/.gitkeep
  src/pages/siniddo/call-back/.gitkeep
  src/pages/siniddo/guide-line/.gitkeep
  src/pages/siniddo/hello-call/.gitkeep
  src/pages/siniddo/mypage/.gitkeep
  src/pages/siniddo/point/.gitkeep
  src/provider/.gitkeep
  src/routes/components/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/setupTests.ts
  src/store/.gitkeep
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 📦 Environment

#3 FE 개발 환경 세팅 및 폴더구조 세팅 (#2)
  .babelrc
  .eslintrc.json
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc.json
  index.html
  jest.config.ts
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  public/vite.svg
  src/App.tsx
  src/__test__/.gitkeep
  src/api/hooks/common/auth/.gitkeep
  src/api/hooks/guard/guide-line/.gitkeep
  src/api/hooks/guard/mypage/.gitkeep
  src/api/hooks/guard/point/.gitkeep
  src/api/hooks/guard/register/.gitkeep
  src/api/hooks/guard/review/.gitkeep
  src/api/hooks/siniddo/call-back/.gitkeep
  src/api/hooks/siniddo/guide-line/.gitkeep
  src/api/hooks/siniddo/hello-call/.gitkeep
  src/api/hooks/siniddo/mypage/.gitkeep
  src/api/hooks/siniddo/point/.gitkeep
  src/api/instance/index.ts
  src/assets/react.svg
  src/components/features/login/index.tsx
  src/components/home/index.tsx
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/mocks/.gitkeep
  src/pages/guard/guide-line/.gitkeep
  src/pages/guard/mypage/.gitkeep
  src/pages/guard/point/.gitkeep
  src/pages/guard/register/.gitkeep
  src/pages/guard/review/.gitkeep
  src/pages/siniddo/call-back/.gitkeep
  src/pages/siniddo/guide-line/.gitkeep
  src/pages/siniddo/hello-call/.gitkeep
  src/pages/siniddo/mypage/.gitkeep
  src/pages/siniddo/point/.gitkeep
  src/provider/.gitkeep
  src/routes/components/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/setupTests.ts
  src/store/.gitkeep
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 📖 Docs, 📦 Environment

#4 FE 개발 환경 세팅 및 폴더구조 세팅 (#2) (#3)
  .babelrc
  .eslintrc.json
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc.json
  index.html
  jest.config.ts
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  public/vite.svg
  src/App.tsx
  src/__test__/.gitkeep
  src/api/hooks/common/auth/.gitkeep
  src/api/hooks/guard/guide-line/.gitkeep
  src/api/hooks/guard/mypage/.gitkeep
  src/api/hooks/guard/point/.gitkeep
  src/api/hooks/guard/register/.gitkeep
  src/api/hooks/guard/review/.gitkeep
  src/api/hooks/siniddo/call-back/.gitkeep
  src/api/hooks/siniddo/guide-line/.gitkeep
  src/api/hooks/siniddo/hello-call/.gitkeep
  src/api/hooks/siniddo/mypage/.gitkeep
  src/api/hooks/siniddo/point/.gitkeep
  src/api/instance/index.ts
  src/assets/react.svg
  src/components/features/login/index.tsx
  src/components/home/index.tsx
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/mocks/.gitkeep
  src/pages/guard/guide-line/.gitkeep
  src/pages/guard/mypage/.gitkeep
  src/pages/guard/point/.gitkeep
  src/pages/guard/register/.gitkeep
  src/pages/guard/review/.gitkeep
  src/pages/siniddo/call-back/.gitkeep
  src/pages/siniddo/guide-line/.gitkeep
  src/pages/siniddo/hello-call/.gitkeep
  src/pages/siniddo/mypage/.gitkeep
  src/pages/siniddo/point/.gitkeep
  src/provider/.gitkeep
  src/routes/components/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/setupTests.ts
  src/store/.gitkeep
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 📖 Docs, 📦 Environment

#6 Feat/issue #5
  src/App.tsx
  src/styles/global/index.ts
Labels: 📦 Environment, 🎨 Design

#8 Global Style 작성 및 공통 컴포넌트 제작
  src/App.tsx
  src/styles/global/index.ts
Labels: ✨ Feature, 🎨 Design

#9 Global Style 작성 및 공통 컴포넌트 제작
  src/App.tsx
  src/styles/global/index.ts
Labels: ✨ Feature, 🎨 Design

#11 [3주차] FE 추기 파일 세팅 및 폴더구조 세팅
  .babelrc
  .eslintrc.json
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc.json
  index.html
  jest.config.ts
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  public/vite.svg
  src/App.tsx
  src/__test__/.gitkeep
  src/api/hooks/common/auth/.gitkeep
  src/api/hooks/guard/guide-line/.gitkeep
  src/api/hooks/guard/mypage/.gitkeep
  src/api/hooks/guard/point/.gitkeep
  src/api/hooks/guard/register/.gitkeep
  src/api/hooks/guard/review/.gitkeep
  src/api/hooks/siniddo/call-back/.gitkeep
  src/api/hooks/siniddo/guide-line/.gitkeep
  src/api/hooks/siniddo/hello-call/.gitkeep
  src/api/hooks/siniddo/mypage/.gitkeep
  src/api/hooks/siniddo/point/.gitkeep
  src/api/instance/index.ts
  src/assets/react.svg
  src/components/features/login/index.tsx
  src/components/home/index.tsx
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/mocks/.gitkeep
  src/pages/guard/guide-line/.gitkeep
  src/pages/guard/mypage/.gitkeep
  src/pages/guard/point/.gitkeep
  src/pages/guard/register/.gitkeep
  src/pages/guard/review/.gitkeep
  src/pages/siniddo/call-back/.gitkeep
  src/pages/siniddo/guide-line/.gitkeep
  src/pages/siniddo/hello-call/.gitkeep
  src/pages/siniddo/mypage/.gitkeep
  src/pages/siniddo/point/.gitkeep
  src/provider/.gitkeep
  src/routes/components/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/setupTests.ts
  src/store/.gitkeep
  src/styles/global/index.ts
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨ Feature, 📦 Environment, 🎨 Design

#16 메인페이지 UI 구현
  package.json
  pnpm-lock.yaml
  src/assets/main/kakao.svg
  src/assets/main/star-icon.svg
  src/components/features/login-button/index.tsx
  src/components/features/login/index.tsx
  src/components/features/review-box/index.tsx
  src/components/home/index.tsx
  src/pages/common/main/index.tsx
  src/routes/index.tsx
Labels: 🎨 Design

#19 배포 자동화 및 eslint 테스트 자동화 기능 구현
  .eslintignore
  .eslintrc.json
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  public/mockServiceWorker.js
  src/main.tsx
  tsconfig.json
Labels: 🚀 Deploy, 📦 Environment

#20 마이페이지 UI 구현 (구성 컴포넌트 추가)
  package-lock.json
  src/components/features/mypage/PointBox/index.tsx
  src/components/features/mypage/ProfileBox/index.tsx
  src/components/features/mypage/UseDetail/index.tsx
  src/pages/siniddo/mypage/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: 🎨 Design

#22 회원가입 페이지 UI 구현
  package-lock.json
  src/components/features/login/index.tsx
  src/components/features/mypage/UseDetail/index.tsx
  src/components/features/register/register-fields.tsx
  src/components/features/register/register-type.tsx
  src/components/features/register/tos/index.tsx
  src/components/features/register/tos/tos-guard.tsx
  src/components/features/register/tos/tos-siniddo.tsx
  src/components/home/index.tsx
  src/pages/common/register/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  vite.config.ts
Labels: 🎨 Design
