Repository kakao-tech-campus-2nd-step3/Team8_FE, pull requests merged in 2024-10, with the labels that each got.

#32 시니또용 콜백 페이지 UI 구현
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/siniddo/call-back/detail/assets/arrow-outline.png
  src/pages/siniddo/call-back/detail/components/guide-line-list/guide-line-button.tsx
  src/pages/siniddo/call-back/detail/components/guide-line-list/index.tsx
  src/pages/siniddo/call-back/detail/components/menu/post-accept/index.tsx
  src/pages/siniddo/call-back/detail/components/menu/pre-accept/index.tsx
  src/pages/siniddo/call-back/detail/data/guide-line/index.ts
  src/pages/siniddo/call-back/detail/index.tsx
  src/pages/siniddo/call-back/list/assets/arrow.png
  src/pages/siniddo/call-back/list/components/request-row/index.tsx
  src/pages/siniddo/call-back/list/data/mock/index.ts
  src/pages/siniddo/call-back/list/index.tsx
  src/pages/siniddo/guide-line/components/container/index.tsx
  src/pages/siniddo/guide-line/data/categories.ts/index.ts
  src/pages/siniddo/guide-line/data/mock/index.ts
  src/pages/siniddo/guide-line/index.tsx
  src/shared/components/common/button/index.tsx
  src/shared/components/features/precaution/index.tsx
Labels: 🎨 Design

#31 안부전화 서비스 요청 리스트 구현
  src/app/routes/path.ts
  src/pages/siniddo/hello-call/.gitkeep
  src/pages/siniddo/hello-call/assets/arrow-icon.svg
  src/pages/siniddo/hello-call/components/request-list/index.tsx
  src/pages/siniddo/hello-call/index.tsx
Labels: 🎨 Design

#30 시니어 등록 페이지 UI 구현 및 공통 컴포넌트(버튼) 생성
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/guard/register/components/senior-info/senior-info-box/index.tsx
  src/pages/guard/register/data/index.tsx
  src/pages/guard/register/index.tsx
  src/pages/guard/register/types/index.tsx
  src/pages/guard/service-history/components/historydetail/index.tsx
  src/shared/theme/global/index.ts
Labels: ✨ Feature, 🎨 Design

#36 안부전화 서비스 UI 구현
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  README.md
  package.json
  pnpm-lock.yaml
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/siniddo/hello-call/hello-call-list/assets/arrow-icon.svg
  src/pages/siniddo/hello-call/hello-call-list/components/request-list/index.tsx
  src/pages/siniddo/hello-call/hello-call-list/index.tsx
  src/pages/siniddo/hello-call/hello-call-report/assets/calendar-icon.svg
  src/pages/siniddo/hello-call/hello-call-report/assets/clock-icon.svg
  src/pages/siniddo/hello-call/hello-call-report/assets/file-icon.svg
  src/pages/siniddo/hello-call/hello-call-report/components/report-detail/index.tsx
  src/pages/siniddo/hello-call/hello-call-report/index.tsx
  src/pages/siniddo/hello-call/hello-call-report/test/mock/index.ts
  src/pages/siniddo/hello-call/hello-call-service/assets/calendar-icon.svg
  src/pages/siniddo/hello-call/hello-call-service/assets/clock-icon.svg
  src/pages/siniddo/hello-call/hello-call-service/assets/speaker-icon.svg
  src/pages/siniddo/hello-call/hello-call-service/assets/title-icon.png
  src/pages/siniddo/hello-call/hello-call-service/components/service-detail/index.tsx
  src/pages/siniddo/hello-call/hello-call-service/data/notice/index.ts
  src/pages/siniddo/hello-call/hello-call-service/index.tsx
  src/pages/siniddo/hello-call/hello-call-service/test/mock/index.ts
  src/shared/components/features/notice/index.tsx
  src/shared/styles/reset.css
Labels: 🎨 Design

#44 회원가입 페이지 UI 수정
  package.json
  pnpm-lock.yaml
  src/pages/common/register/components/register-fields/form-fileds/index.tsx
  src/pages/common/register/components/register-fields/index.tsx
  src/pages/common/register/components/register-type/index.tsx
  src/pages/common/register/components/register-type/type-button.tsx/index.tsx
  src/pages/common/register/components/tos/content/index.tsx
  src/pages/common/register/components/tos/index.tsx
  src/pages/common/register/components/tos/sinitto/index.tsx
  src/pages/common/register/index.tsx
  src/pages/common/register/types/index.tsx
Labels: 🎨 Design

#43 헤더 UI 구현
  src/shared/components/features/header/asset/ic_arrow_back.svg
  src/shared/components/features/header/index.tsx
Labels: ✨ Feature, 🎨 Design

#42 시니또 평가 페이지 UI 구현
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/guard/review/asset/star-icon.svg
  src/pages/guard/review/index.tsx
Labels: ✨ Feature, 🎨 Design

#46 5주차 코드리뷰 피드백 반영
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/siniddo/call-back/detail/components/menu/pre-accept/index.tsx
  src/shared/components/common/button/index.tsx
  src/shared/theme/global/index.ts
Labels: ✨ Feature, 🎨 Design, ♻️ Refactoring

#50 Devlop 브랜치 pull , 필요없는 파일 제거
  package-lock.json
  src/pages/siniddo/call-back/.gitkeep
Labels: 😡 Bug Fix, 🔥 Remove

#52 Develop
  package.json
  pnpm-lock.yaml
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/common/register/components/register-fields/form-fileds/index.tsx
  src/pages/common/register/components/register-fields/index.tsx
  src/pages/common/register/components/register-type/index.tsx
  src/pages/common/register/components/register-type/type-button.tsx/index.tsx
  src/pages/common/register/components/tos/content/index.tsx
  src/pages/common/register/components/tos/index.tsx
  src/pages/common/register/components/tos/sinitto/index.tsx
  src/pages/common/register/index.tsx
  src/pages/common/register/types/index.tsx
  src/pages/guard/review/asset/star-icon.svg
  src/pages/guard/review/index.tsx
  src/pages/siniddo/call-back/detail/components/menu/pre-accept/index.tsx
  src/shared/components/common/button/index.tsx
  src/shared/components/features/header/asset/ic_arrow_back.svg
  src/shared/components/features/header/index.tsx
  src/shared/theme/global/index.ts
Labels: 🚀 Deploy

#59 [기능구현] 회원가입
  src/pages/common/register/api/hooks/useRegister.ts
  src/pages/common/register/index.tsx
  src/shared/api/auth/user-register.ts
  src/shared/api/instance/index.ts
  src/shared/utils/storage/index.ts
Labels: ✨ Feature, 📡 API

#61 카카오 로그인 기능 구현
  .github/workflows/deploy.yml
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/common/main/MainPage.tsx
  src/pages/common/main/components/login-button/index.tsx
  src/pages/common/redirect/components/redirect-section/RedirectSection.tsx
  src/pages/common/redirect/index.ts
  src/pages/common/redirect/store/api/kakao-callback.api.ts
  src/pages/common/redirect/store/hooks/useGetKakaoCallback.ts
  src/pages/common/redirect/ui/RedirectPage.tsx
  src/pages/guard/guide-line/.gitkeep
  src/pages/guard/guide-line/store/api/view-specific-guideline.api.ts
  src/pages/guard/guide-line/store/hooks/getViewSpecificGuideline.ts
  src/shared/api/instance/index.ts
  src/shared/constants/.gitkeep
  src/shared/constants/URI.ts
Labels: 🚀 Deploy, ✨ Feature

#76 안부전화 api 코드 구현 (코드리뷰 수정 반영)
  src/pages/guard/hello-call-report/api/hooks/usePostApplyHelloCall.ts
  src/pages/guard/hello-call-report/api/hooks/usePostCostHelloCall.ts
  src/pages/guard/hello-call-report/api/hooks/usePutHelloCall.ts
  src/pages/sinitto/hello-call-list/api/hooks/useGetServiceList.ts
  src/pages/sinitto/hello-call-list/api/hooks/usePutCancelHelloCall.ts
Labels: 😡 Bug Fix, 🔥 Remove

#80 [기능구현] 마이페이지
  src/pages/guard/mypage/GuardMyPage.tsx
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
  src/pages/guard/mypage/store/api/guard-information.api.ts
  src/pages/guard/mypage/store/api/index.ts
  src/pages/guard/mypage/store/hooks/index.ts
  src/pages/guard/mypage/store/hooks/useGetGuardInformation.ts
  src/pages/sinitto/call-back/list/data/index.ts
  src/pages/sinitto/call-back/list/data/mock/index.ts
  src/pages/sinitto/guide-line/data/index.ts
  src/pages/sinitto/guide-line/data/mock/index.ts
  src/pages/sinitto/mypage/SinittoMypage.tsx
  src/pages/sinitto/mypage/components/account-info-box/AccountInfoBox.tsx
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/pages/sinitto/mypage/data/detail/dummy-data.ts
  src/pages/sinitto/mypage/store/api/index.ts
  src/pages/sinitto/mypage/store/api/sinitto-information.api.ts
  src/pages/sinitto/mypage/store/hooks/index.ts
  src/pages/sinitto/mypage/store/hooks/useSinittoInfo.ts
  src/shared/api/point/index.ts
  src/shared/api/point/point-log.api.ts
  src/shared/api/point/point.api.ts
  src/shared/assets/point-log-icon.png
  src/shared/assets/react.svg
  src/shared/components/features/mypage/hooks/index.ts
  src/shared/components/features/mypage/hooks/useToggleDetailBox.ts
  src/shared/components/features/mypage/index.ts
  src/shared/components/features/mypage/point-box/PointBox.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
  src/shared/components/features/mypage/point-log-box/index.ts
  src/shared/components/features/mypage/use-detail/UseDetailBox.tsx
  src/shared/components/features/mypage/use-detail/index.ts
  src/shared/hooks/index.ts
  src/shared/hooks/point/index.ts
  src/shared/hooks/point/pointStatusMapping.ts
  src/shared/hooks/point/useChargePoint.ts
  src/shared/hooks/point/useGetPointInfo.ts
  src/shared/hooks/point/useGetPointLogs.ts
  src/shared/hooks/point/useWithdrawPoint.ts
Labels: ✨ Feature, 📡 API

#83 [Fix] 마이페이지 빌드 오류 해결
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
Labels: 😡 Bug Fix

#88 시니또용 콜백 페이지 api 및 기능 구현
  src/pages/sinitto/call-back/detail/CallBackDetailPage.tsx
  src/pages/sinitto/call-back/detail/api/accept-call-back.api.ts
  src/pages/sinitto/call-back/detail/api/cancel-call-back.api.ts
  src/pages/sinitto/call-back/detail/api/complete-call-back.api.ts
  src/pages/sinitto/call-back/detail/api/get-accepted.api.ts
  src/pages/sinitto/call-back/detail/api/hooks/index.ts
  src/pages/sinitto/call-back/detail/api/hooks/useAcceptCallback.ts
  src/pages/sinitto/call-back/detail/api/hooks/useCancelCallback.ts
  src/pages/sinitto/call-back/detail/api/hooks/useCompleteCallback.ts
  src/pages/sinitto/call-back/detail/api/hooks/useGetAccepted.ts
  src/pages/sinitto/call-back/detail/api/index.ts
  src/pages/sinitto/call-back/detail/components/guide-line-list/GuideLineList.tsx
  src/pages/sinitto/call-back/detail/components/guide-line-list/guide-line-button.tsx
  src/pages/sinitto/call-back/detail/components/menu/CallbackMenu.tsx
  src/pages/sinitto/call-back/detail/components/menu/index.ts
  src/pages/sinitto/call-back/detail/data/guide-line/guid-line-categories.ts
  src/pages/sinitto/call-back/list/CallBackListPage.tsx
  src/pages/sinitto/call-back/list/api/callback-list.api.ts
  src/pages/sinitto/call-back/list/api/get-call-backs.api.ts
  src/pages/sinitto/call-back/list/api/hooks/index.ts
  src/pages/sinitto/call-back/list/api/hooks/useGetCallbacks.ts
  src/pages/sinitto/call-back/list/api/index.ts
  src/pages/sinitto/call-back/list/api/types/callbacks.response.ts
  src/pages/sinitto/call-back/list/api/types/index.ts
  src/pages/sinitto/call-back/list/components/request-row/RequestRow.tsx
  src/pages/sinitto/guide-line/SinittoGuideLinePage.tsx
  src/pages/sinitto/guide-line/api/get-guideline.api.ts
  src/pages/sinitto/guide-line/api/hooks/index.ts
  src/pages/sinitto/guide-line/api/hooks/useGetGuideline.ts
  src/pages/sinitto/guide-line/api/index.ts
  src/pages/sinitto/guide-line/api/types/guideline.response.ts
  src/pages/sinitto/guide-line/api/types/index.ts
  src/pages/sinitto/guide-line/data/categories/categories.ts
  src/shared/api/get-call-back.api.ts
  src/shared/api/hooks/index.ts
  src/shared/api/hooks/useGetCallback.ts
  src/shared/api/index.ts
  src/shared/types/callback.response.ts
  src/shared/types/index.ts
  src/shared/utils/handle-callback-error.ts
  src/shared/utils/index.ts
Labels: ✨ Feature, 📡 API

#87 안부전화 신청하기 포인트 계산
  .gitignore
  src/pages/common/redirect/store/api/kakao-callback.api.ts
  src/pages/guard/hello-call-apply/HelloCallApplyPage.tsx
  src/pages/guard/hello-call-apply/api/apply-hello-call.api.ts
  src/pages/guard/hello-call-apply/api/cost-hello-call.api.ts
  src/pages/guard/hello-call-apply/api/hooks/index.ts
  src/pages/guard/hello-call-apply/api/hooks/usePostApplyHelloCall.ts
  src/pages/guard/hello-call-apply/api/hooks/usePostCostHelloCall.ts
  src/pages/guard/hello-call-apply/api/index.ts
  src/pages/guard/hello-call-apply/api/types/apply-hello-call.reqeust.ts
  src/pages/guard/hello-call-apply/api/types/apply-hello-call.response.ts
  src/pages/guard/hello-call-apply/api/types/cost-hello-call.request.ts
  src/pages/guard/hello-call-apply/api/types/cost-hello-call.response.ts
  src/pages/guard/hello-call-apply/api/types/index.ts
  src/pages/guard/hello-call-apply/components/index.ts
  src/pages/guard/hello-call-apply/components/notice-area/NoticeArea.tsx
  src/pages/guard/hello-call-apply/components/notice-area/index.ts
  src/pages/guard/hello-call-apply/components/select-senior/SelectSenior.tsx
  src/pages/guard/hello-call-apply/components/select-senior/index.ts
  src/pages/guard/hello-call-apply/components/service-period/ServicePeriod.tsx
  src/pages/guard/hello-call-apply/components/service-time/index.ts
  src/pages/guard/hello-call-apply/components/service-total/ServiceTotal.tsx
  src/pages/guard/hello-call-apply/components/service-using-time/ServiceUsingTime.tsx
  src/pages/guard/hello-call-apply/components/service-using-time/index.ts
  src/pages/guard/hello-call-apply/components/tell-to-sinitto/TellToSinitto.tsx
  src/pages/guard/hello-call-apply/components/tell-to-sinitto/index.ts
  src/pages/guard/hello-call-apply/data/day-data.ts
  src/pages/guard/hello-call-apply/data/index.ts
  src/pages/guard/hello-call-apply/data/use-time-data.ts
  src/pages/guard/hello-call-apply/hooks/index.ts
  src/pages/guard/hello-call-apply/hooks/useSlots.ts
  src/pages/guard/hello-call-apply/hooks/useSortDays.ts
  src/pages/guard/hello-call-apply/index.ts
  src/shared/theme/global/index.ts
Labels: ✨ Feature, 📡 API

#91 코드리뷰 반영 및 헤더기능 구현
  src/app/routes/index.tsx
  src/pages/common/register/RegisterPage.tsx
  src/pages/common/register/api/index.ts
  src/pages/common/register/index.ts
  src/pages/common/register/store/api/index.ts
  src/pages/common/register/store/api/user-register.ts
  src/pages/common/register/store/hooks/index.ts
  src/pages/common/register/store/hooks/useRegister.ts
  src/shared/api/instance/index.ts
  src/shared/components/common/layout/Layout.tsx
  src/shared/components/features/header/Header.tsx
  src/shared/utils/storage/index.ts
Labels: ✨ Feature, ♻️ Refactoring

#93 안부전화 신청 기능 구현 및 기타 코드 수정
  src/App.tsx
  src/pages/guard/hello-call-apply/HelloCallApplyPage.tsx
  src/pages/guard/hello-call-apply/api/index.ts
  src/pages/guard/hello-call-apply/api/types/apply-hello-call.reqeust.ts
  src/pages/guard/hello-call-apply/components/index.ts
  src/pages/guard/hello-call-apply/components/select-senior/SelectSenior.tsx
  src/pages/guard/hello-call-apply/components/service-apply/ServiceApply.tsx
  src/pages/guard/hello-call-apply/components/service-apply/index.ts
  src/pages/guard/hello-call-apply/components/service-period/ServicePeriod.tsx
  src/pages/guard/hello-call-apply/components/tell-to-sinitto/TellToSinitto.tsx
  src/pages/guard/hello-call-apply/hooks/index.ts
  src/pages/guard/hello-call-apply/hooks/useHelloCallState.ts
  src/pages/guard/mypage/api/all-senior-info.api.ts
  src/pages/guard/mypage/api/guard-information.api.ts
  src/pages/guard/mypage/api/hooks/index.ts
  src/pages/guard/mypage/api/hooks/useGetAllSeniorInfo.ts
  src/pages/guard/mypage/api/hooks/useGetGuardInformation.ts
  src/pages/guard/mypage/api/index.ts
  src/pages/guard/mypage/api/types/all-senior-info.response.ts
  src/pages/guard/mypage/api/types/guard-infomation.response.ts
  src/pages/guard/mypage/api/types/index.ts
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
  src/pages/guard/mypage/index.ts
  src/pages/guard/mypage/store/api/guard-information.api.ts
  src/pages/guard/mypage/store/api/index.ts
  src/shared/api/instance/index.ts
  src/shared/index.ts
  src/shared/provider/index.ts
  src/shared/provider/senior-info/SeniorInfo.tsx
  src/shared/provider/senior-info/index.ts
  src/shared/types/.gitkeep
Labels: ✨ Feature, 📡 API

#96 refresh token 발급 기능 구현
  src/shared/api/instance/index.ts
Labels: 😡 Bug Fix, 📡 API

#98 [기능구현] 보호자 시니어 추가 페이지 + 기타 코드 수정
  src/pages/common/register/RegisterPage.tsx
  src/pages/guard/register/SeniorRegisterPage.tsx
  src/pages/guard/register/api/hooks/index.ts
  src/pages/guard/register/api/hooks/useAddSeniorInfo.ts
  src/pages/guard/register/api/hooks/useDeleteSeniorInfo.ts
  src/pages/guard/register/api/hooks/useEditSeniorInfo.ts
  src/pages/guard/register/api/index.ts
  src/pages/guard/register/api/senior-info.api.ts
  src/pages/guard/register/api/types/index.ts
  src/pages/guard/register/api/types/senior-register.type.ts
  src/pages/guard/register/components/index.ts
  src/pages/guard/register/components/senior-info/senior-info-box/SeniorInfo.tsx
  src/pages/guard/register/components/senior-register-box/SeniorFormField.tsx
  src/pages/guard/register/components/senior-register-box/SeniorRegisterBox.tsx
  src/pages/guard/register/components/senior-register-box/index.ts
  src/pages/guard/register/index.ts
  src/pages/guard/register/types/index.tsx
  src/shared/assets/delete-icon.svg
  src/shared/assets/edit-icon.svg
  src/shared/assets/index.ts
  src/shared/components/features/header/Header.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
  src/shared/hooks/index.ts
  src/shared/index.ts
  src/shared/utils/index.ts
  src/shared/utils/phone-number/formatPhoneNumber.ts
  src/shared/utils/phone-number/index.ts
Labels: ✨ Feature, 🎨 Design, 📡 API

#99 회원가입 및 로그인 기능 수정
  src/App.tsx
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/common/redirect/api/index.ts
  src/pages/common/redirect/api/kakao-callback.api.ts
  src/pages/common/redirect/components/redirect-section/RedirectSection.tsx
  src/pages/common/redirect/hooks/index.ts
  src/pages/common/redirect/hooks/useGetKakaoCallback.ts
  src/pages/common/redirect/index.ts
  src/pages/common/register/RegisterPage.tsx
  src/pages/guard/guard-main/GuardMainPage.tsx
  src/pages/guard/guard-main/index.ts
  src/pages/guard/index.ts
  src/pages/sinitto/index.ts
  src/pages/sinitto/sinitto-main/SinittoMainPage.tsx
  src/pages/sinitto/sinitto-main/index.ts
  src/shared/hooks/index.ts
  src/shared/provider/auth/Auth.tsx
  src/shared/provider/auth/index.ts
  src/shared/provider/index.ts
Labels: 😡 Bug Fix, ✨ Feature

#103 보호자 메인페이지 ui 구현
  src/pages/assets/guard-main/hello-call.png
  src/pages/assets/guard-main/list.svg
  src/pages/assets/index.ts
  src/pages/assets/shared/IconArrow.tsx
  src/pages/assets/shared/index.ts
  src/pages/assets/shared/user.svg
  src/pages/guard/guard-main/GuardMainPage.tsx
  src/pages/guard/guard-main/components/guideline-list/GuideLineList.tsx
  src/pages/guard/guard-main/components/guideline-list/index.ts
  src/pages/guard/guard-main/components/header/Header.tsx
  src/pages/guard/guard-main/components/header/index.ts
  src/pages/guard/guard-main/components/hello-call-apply/HelloCallApply.tsx
  src/pages/guard/guard-main/components/hello-call-apply/index.ts
  src/pages/guard/guard-main/components/index.ts
  src/shared/assets/arrow.svg
  src/shared/components/common/guide-line-button/GuideLineButton.tsx
  src/shared/components/common/guide-line-button/index.ts
  src/shared/components/common/index.ts
  src/shared/components/features/header/Header.tsx
  src/shared/components/features/header/index.ts
Labels: 🎨 Design

#104 시니또 메인페이지 ui 구현
  src/pages/assets/shared/hello-call.png
  src/pages/assets/sinitto-main/call.svg
  src/pages/guard/guard-main/components/hello-call-apply/HelloCallApply.tsx
  src/pages/sinitto/sinitto-main/SinittoMainPage.tsx
  src/pages/sinitto/sinitto-main/components/common/call-back-apply/CallBackApply.tsx
  src/pages/sinitto/sinitto-main/components/common/call-back-apply/index.ts
  src/pages/sinitto/sinitto-main/components/common/header/Header.tsx
  src/pages/sinitto/sinitto-main/components/common/header/index.ts
  src/pages/sinitto/sinitto-main/components/common/hello-call-apply/HelloCallApply.tsx
  src/pages/sinitto/sinitto-main/components/common/hello-call-apply/index.ts
  src/pages/sinitto/sinitto-main/components/common/index.ts
  src/pages/sinitto/sinitto-main/components/features/index.ts
  src/pages/sinitto/sinitto-main/components/features/response-box/ResponseBox.tsx
  src/pages/sinitto/sinitto-main/components/features/response-box/index.ts
  src/pages/sinitto/sinitto-main/components/index.ts
  src/pages/sinitto/sinitto-main/index.ts
Labels: 🎨 Design

#105 [기능구현] 보호자용 가이드라인 페이지
  src/app/routes/index.tsx
  src/app/routes/path.ts
  src/pages/guard/guard-main/GuardMainPage.tsx
  src/pages/guard/guard-main/components/guideline-list/GuideLineList.tsx
  src/pages/guard/guard-main/components/header/Header.tsx
  src/pages/guard/guide-line/GuideLinePage.tsx
  src/pages/guard/guide-line/api/add-guideline.api.ts
  src/pages/guard/guide-line/api/hooks/index.ts
  src/pages/guard/guide-line/api/hooks/useAddGuideline.ts
  src/pages/guard/guide-line/api/hooks/useGetSeniorAllGuideines.ts
  src/pages/guard/guide-line/api/hooks/useModifyGuideline.ts
  src/pages/guard/guide-line/api/index.ts
  src/pages/guard/guide-line/api/modify-guideline.api.ts
  src/pages/guard/guide-line/api/view-senior-all-guideline.api.ts
  src/pages/guard/guide-line/components/guide-info-box/GuideLineInfo.tsx
  src/pages/guard/guide-line/components/guide-info-box/index.ts
  src/pages/guard/guide-line/components/guide-register-box/GuideFormField.tsx
  src/pages/guard/guide-line/components/guide-register-box/GuidelineRegisterBox.tsx
  src/pages/guard/guide-line/components/guide-register-box/index.ts
  src/pages/guard/guide-line/components/index.ts
  src/shared/assets/arrow-icon.svg
  src/shared/assets/index.ts
  src/shared/components/common/guide-line-button/GuideLineButton.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
  src/shared/utils/storage/index.ts
Labels: ✨ Feature, 📡 API

#108 헤더 ui 수정
  src/shared/assets/arrow-back.svg
  src/shared/components/features/header/Header.tsx
  src/shared/components/features/header/asset/ic_arrow_back.svg
Labels: 🎨 Design

#111 가이드라인 페이지 기능 추가 및 기타 코드 수정
  src/pages/guard/guard-main/GuardMainPage.tsx
  src/pages/guard/guide-line/GuideLinePage.tsx
  src/pages/guard/guide-line/api/delete-guideline.api.ts
  src/pages/guard/guide-line/api/hooks/index.ts
  src/pages/guard/guide-line/api/hooks/useDeleteGuideline.ts
  src/pages/guard/guide-line/api/index.ts
  src/pages/guard/guide-line/api/view-senior-all-guideline.api.ts
  src/pages/guard/guide-line/components/guide-info-box/GuideLineInfo.tsx
  src/pages/guard/guide-line/components/guide-register-box/GuideFormField.tsx
  src/pages/guard/guide-line/components/guide-register-box/GuidelineRegisterBox.tsx
  src/pages/guard/review/SinittoReviewPage.tsx
Labels: ✨ Feature, 📡 API, ♻️ Refactoring

#122 가이드라인, 시니어 추가 페이지 UI 수정
  src/pages/guard/guide-line/GuideLinePage.tsx
  src/pages/guard/guide-line/components/guide-info-box/GuideLineInfo.tsx
  src/pages/guard/guide-line/components/guide-register-box/GuidelineRegisterBox.tsx
  src/pages/guard/register/SeniorRegisterPage.tsx
  src/pages/guard/register/components/senior-info/senior-info-box/SeniorInfo.tsx
  src/pages/guard/register/components/senior-register-box/SeniorRegisterBox.tsx
Labels: 🎨 Design

#125 배포된 주소로 로그인 기능 구현
  src/pages/common/main/MainPage.tsx
  src/pages/common/main/components/login-button/LoginButton.tsx
  src/pages/common/redirect/components/redirect-section/RedirectSection.tsx
Labels: ✨ Feature

#126 로그인 관련 수정사항 롤백
  src/pages/common/main/MainPage.tsx
  src/pages/common/main/components/login-button/LoginButton.tsx
  src/pages/common/redirect/RedirectPage.tsx
  src/pages/common/redirect/components/redirect-section/RedirectSection.tsx
Labels: 😡 Bug Fix

#128 시니또 메인 페이지 기능 수정
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/pages/sinitto/call-back/list/api/get-call-backs.api.ts
  src/pages/sinitto/call-back/list/api/index.ts
  src/pages/sinitto/call-back/list/index.ts
  src/pages/sinitto/hello-call-list/HelloCallListPage.tsx
  src/pages/sinitto/hello-call-list/api/hooks/useGetServiceList.ts
  src/pages/sinitto/hello-call-list/api/service-list.api.ts
  src/pages/sinitto/hello-call-list/components/call-request/CallRequest.tsx
  src/pages/sinitto/hello-call-list/index.ts
  src/pages/sinitto/mypage/SinittoMypage.tsx
  src/pages/sinitto/mypage/api/hooks/index.ts
  src/pages/sinitto/mypage/api/hooks/useSinittoInfo.ts
  src/pages/sinitto/mypage/api/index.ts
  src/pages/sinitto/mypage/api/sinitto-information.api.ts
  src/pages/sinitto/mypage/api/types/index.ts
  src/pages/sinitto/mypage/api/types/sinitto-infromation.response.ts
  src/pages/sinitto/mypage/components/account-info-box/AccountInfoBox.tsx
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/pages/sinitto/mypage/index.ts
  src/pages/sinitto/mypage/store/api/index.ts
  src/pages/sinitto/mypage/store/api/sinitto-information.api.ts
  src/pages/sinitto/mypage/store/servers/index.ts
  src/pages/sinitto/sinitto-main/SinittoMainPage.tsx
  src/pages/sinitto/sinitto-main/api/hooks/index.ts
  src/pages/sinitto/sinitto-main/api/hooks/useGetSinittoInfo.ts
  src/pages/sinitto/sinitto-main/api/index.ts
  src/pages/sinitto/sinitto-main/api/sinitto-info.api.ts
  src/pages/sinitto/sinitto-main/api/types/index.ts
  src/pages/sinitto/sinitto-main/api/types/sinitto-info.response.ts
  src/pages/sinitto/sinitto-main/components/common/call-back-apply/CallBackApply.tsx
  src/pages/sinitto/sinitto-main/components/common/header/Header.tsx
  src/pages/sinitto/sinitto-main/components/common/hello-call-apply/HelloCallApply.tsx
  src/pages/sinitto/sinitto-main/components/common/index.ts
  src/pages/sinitto/sinitto-main/components/common/sinitto-name/SinittoName.tsx
  src/pages/sinitto/sinitto-main/components/common/sinitto-name/index.ts
  src/pages/sinitto/sinitto-main/components/features/response-box/ResponseBox.tsx
  src/pages/sinitto/sinitto-main/index.ts
  src/shared/components/common/index.ts
  src/shared/components/common/visibility-loader/VisibilityLoader.tsx
  src/shared/components/common/visibility-loader/index.ts
  src/shared/provider/index.ts
  src/shared/provider/sinitto-info/SinittoInfo.tsx
  src/shared/provider/sinitto-info/index.ts
Labels: 😡 Bug Fix, ✨ Feature, 📡 API

#129 코드리뷰 반영 + 로그아웃 기능 추가
  src/pages/common/register/store/hooks/useRegister.ts
  src/pages/guard/guard-main/components/guideline-list/GuideLineList.tsx
  src/pages/guard/guard-main/components/header/Header.tsx
  src/pages/guard/guard-main/components/hello-call-apply/HelloCallApply.tsx
  src/pages/guard/guide-line/api/hooks/index.ts
  src/pages/guard/guide-line/api/hooks/useGuidelineInfo.ts
  src/pages/guard/guide-line/components/guide-info-box/GuideLineInfo.tsx
  src/pages/guard/mypage/GuardMyPage.tsx
  src/pages/guard/mypage/components/profile-box/GuardProfileBox.tsx
  src/pages/guard/register/api/hooks/index.ts
  src/pages/guard/register/api/hooks/useSeniorInfo.ts
  src/pages/guard/register/components/senior-info/senior-info-box/SeniorInfo.tsx
  src/pages/sinitto/mypage/SinittoMypage.tsx
  src/pages/sinitto/mypage/components/profile-box/SinittoProfileBox.tsx
  src/shared/api/hooks/index.ts
  src/shared/api/hooks/useLogout.ts
  src/shared/api/index.ts
  src/shared/api/logout.api.ts
  src/shared/api/point/point.api.ts
  src/shared/components/common/button/BasicButton.tsx
  src/shared/components/features/header/Header.tsx
  src/shared/components/features/mypage/index.ts
  src/shared/components/features/mypage/logout-button/Logout.tsx
  src/shared/components/features/mypage/logout-button/index.ts
  src/shared/components/features/mypage/point-box/PointBox.tsx
  src/shared/components/features/mypage/point-log-box/PointLogBox.tsx
  src/shared/hooks/point/useChargePoint.ts
Labels: ✨ Feature, 📡 API, ♻️ Refactoring

#132 더미 로그인 리다이렉트 페이지
  src/app/routes/path.ts
  src/app/routes/router.tsx
  src/pages/common/dummy-redirect/DummyRedirectPage.tsx
  src/pages/common/dummy-redirect/index.ts
  src/pages/common/index.ts
Labels: ✨ Feature
